# Generated by Django 5.0 on 2023-12-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="add",
            name="author",
        ),
        migrations.RemoveField(
            model_name="add",
            name="description",
        ),
        migrations.RemoveField(
            model_name="add",
            name="name",
        ),
        migrations.RemoveField(
            model_name="add",
            name="price",
        ),
    ]
