# Generated by Django 5.0 on 2023-12-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_remove_add_author_remove_add_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="add",
            name="author",
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name="add",
            name="description",
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="add",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="books"),
        ),
        migrations.AddField(
            model_name="add",
            name="name",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="add",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
