# Generated by Django 5.0 on 2023-12-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_add_author_add_description_add_image_add_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="add",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="media/"),
        ),
    ]
