# Generated by Django 5.0 on 2023-12-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_alter_add_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="add",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
