# Generated by Django 5.0 on 2023-12-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0006_alter_add_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="add",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="image/download"),
        ),
    ]
