# Generated by Django 5.0 on 2023-12-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0008_alter_add_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="add",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
