# Generated by Django 5.0 on 2023-12-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0009_add_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue_book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(default=None, max_length=50)),
                ("student_id", models.IntegerField(default=0)),
                ("branch", models.CharField(default=None, max_length=20)),
                ("section", models.CharField(default=None, max_length=100)),
                (
                    "Book_name",
                    models.ImageField(default="default.jpg", upload_to="books"),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("date_of_issue", models.DateField(verbose_name="Date of Issue")),
                ("date_of_return", models.DateField(verbose_name="Date of Return")),
            ],
        ),
    ]
