# Generated by Django 5.0 on 2023-12-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0010_issue_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue_book",
            name="Book_name",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
