# Generated by Django 5.0 on 2023-12-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0011_alter_issue_book_book_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue_book",
            name="Book_id",
            field=models.IntegerField(default=1),
        ),
    ]
