# Generated by Django 4.1.13 on 2024-01-01 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_remove_student_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue_book',
        ),
    ]
