# Generated by Django 4.1.13 on 2024-01-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_remove_student_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='room_no',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
